project_name: StockPlay
output_folder: docs
planning_artifacts: docs
project_knowledge: docs
user_name: Ramkumar
communication_language: English
document_output_language: English
user_skill_level: expert
